### ISSUE TITLE
Occasional hangs at the end of a song

### ISSUE THREAD

**Issue by esteigler** [PromyLOPh/pianobar#503]
Occasionally pianobar will hang at the end/near the end of a song and stop responding to any sort of keyboard input. If I wait a variable amount of time (> 5 minutes) it will occasionally resume. Otherwise I need to ctl-c the process and when I restart it, things are fine.

Pianobar is compiled from source at revision 32151ea899e5b539d3532ddb30333550ffb092b4 running on FreeBSD 10.1. I have the following libraries installed (and it's linked against them):
gnutls-3.2.16_3
libao-1.2.0
libgcrypt-1.6.1_5
json-c-0.11
ffmpeg-2.2.4_4

When it freezes it looks like this:
```
(i) Receiving new playlist... Ok.
|>  "Tell Me" by "Clear View" on "In Search Of Sunrise 6 : Ibiza"
|>  "Runaway (Mat Zo Vocal Remix)" by "Keenen & Anderson" on "The Thrillseekers: Nightmusic Volume 3"
|>  "Road To Perdition" by "Dinka" on "Mykonos Summer Guide"
|>  "Let The Light Shine In" by "Darren Tate &  Jono Grant" on "Nyana"
#   -00:00/06:16
```

If I attach gdb to it and dump the threads I have:
```
(gdb) info threads
  5 Thread 806806400 (LWP 101093/pianobar)  0x00000008030e716a in select () from /lib/libc.so.7
  4 Thread 806807000 (LWP 101171/pianobar)  0x000000080307794a in poll () from /lib/libc.so.7
  3 Thread 807149400 (LWP 101173/pianobar)  0x0000000800a4b8dc in __error () from /lib/libthr.so.3
  2 Thread 807149800 (LWP 101177/pianobar)  0x0000000800a4b8dc in __error () from /lib/libthr.so.3
* 1 Thread 807149c00 (LWP 101179/pianobar)  0x0000000800a4b8dc in __error () from /lib/libthr.so.3
```

Backtraces of all the threads:
```
(gdb) thread apply all bt

Thread 5 (Thread 806806400 (LWP 101093/pianobar)):
#0  0x00000008030e716a in select () from /lib/libc.so.7
#1  0x0000000800a42b32 in select () from /lib/libthr.so.3
#2  0x0000000000409e2a in BarReadline ()
#3  0x0000000000404d50 in main ()

Thread 4 (Thread 806807000 (LWP 101171/pianobar)):
#0  0x000000080307794a in poll () from /lib/libc.so.7
#1  0x0000000800a428a6 in poll () from /lib/libthr.so.3
#2  0x0000000801fad984 in av_write_uncoded_frame_query () from /usr/local/lib/libavformat.so.55
#3  0x0000000801ff981b in av_sdp_create () from /usr/local/lib/libavformat.so.55
#4  0x0000000801f3d517 in ffurl_close () from /usr/local/lib/libavformat.so.55
#5  0x0000000801f63c93 in av_find_input_format () from /usr/local/lib/libavformat.so.55
#6  0x0000000801f62a08 in av_find_input_format () from /usr/local/lib/libavformat.so.55
#7  0x0000000801f3d517 in ffurl_close () from /usr/local/lib/libavformat.so.55
#8  0x0000000801f3e4f3 in avio_seek () from /usr/local/lib/libavformat.so.55
#9  0x0000000801f3f311 in avio_read () from /usr/local/lib/libavformat.so.55
#10 0x0000000801fffe59 in av_get_packet () from /usr/local/lib/libavformat.so.55
#11 0x0000000801f806ca in avformat_get_mov_audio_tags () from /usr/local/lib/libavformat.so.55
#12 0x0000000802000f70 in avformat_free_context () from /usr/local/lib/libavformat.so.55
#13 0x0000000802002190 in av_read_frame () from /usr/local/lib/libavformat.so.55
#14 0x0000000802002002 in av_read_frame () from /usr/local/lib/libavformat.so.55
#15 0x0000000000405625 in BarPlayerThread ()
#16 0x0000000800a404f5 in pthread_create () from /lib/libthr.so.3
#17 0x00007fffdfdfe000 in ?? ()
Error accessing memory address 0x7fffdfffe000: Bad address.

Thread 3 (Thread 807149400 (LWP 101173/pianobar)):
#0  0x0000000800a4b8dc in __error () from /lib/libthr.so.3
#1  0x0000000800a49d9e in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x000000080251cd4b in avfilter_graph_parse_ptr () from /usr/local/lib/libavfilter.so.4
#3  0x0000000800a404f5 in pthread_create () from /lib/libthr.so.3
#4  0x00007fffdfbfd000 in ?? ()
Error accessing memory address 0x7fffdfdfd000: Bad address.

Thread 2 (Thread 807149800 (LWP 101177/pianobar)):
#0  0x0000000800a4b8dc in __error () from /lib/libthr.so.3
#1  0x0000000800a49d9e in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x000000080251cd4b in avfilter_graph_parse_ptr () from /usr/local/lib/libavfilter.so.4
#3  0x0000000800a404f5 in pthread_create () from /lib/libthr.so.3
#4  0x00007fffdf9fc000 in ?? ()
Error accessing memory address 0x7fffdfbfc000: Bad address.

Thread 1 (Thread 807149c00 (LWP 101179/pianobar)):
#0  0x0000000800a4b8dc in __error () from /lib/libthr.so.3
#1  0x0000000800a49d9e in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x000000080251cd4b in avfilter_graph_parse_ptr () from /usr/local/lib/libavfilter.so.4
#3  0x0000000800a404f5 in pthread_create () from /lib/libthr.so.3
#4  0x00007fffdf7fb000 in ?? ()
Error accessing memory address 0x7fffdf9fb000: Bad address.
```

After dumping all of this data and exiting gdb, I allowed the process to resume. This caused it to resume working with the following output:
```
[aac @ 0x807097120] Input buffer exhausted before END element found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x80700f420] stream 0, offset 0x178e64: partial file
[http @ 0x80701f2a0] HTTP error 400 Bad Request
(i) Receiving new playlist... Ok.
|>  "Ride (Tiesto Remix)" by "Cary Brothers" on "In Search Of Sunrise 7 : Asia (Unmixed)"
#   -04:40/07:01
```
Prior to playing the actual song it played an ad.

Let me know if you need any more info.

**Comment by PromyLOPh** [comment]
#498 looks quite similar, have a look.

> Thread 3 (Thread 807149400 (LWP 101173/pianobar)):
> #0  0x0000000800a4b8dc in __error () from /lib/libthr.so.3
> #1  0x0000000800a49d9e in _pthread_cond_wait () from /lib/libthr.so.3
> #2  0x000000080251cd4b in avfilter_graph_parse_ptr () from /usr/local/lib/libavfilter.so.4
> #3  0x0000000800a404f5 in pthread_create () from /lib/libthr.so.3
> #4  0x00007fffdfbfd000 in ?? ()
Might not be related, but there seems to be an issue with ffmpeg’s
threading stuff too.

**Comment by esteigler** [comment]
I upgraded to ffmpeg-2.3.6 and will update if that fixes it or if I can still reproduce it.

**Comment by esteigler** [comment]
I haven't been able to reproduce it with ffmpeg-2.3.6. I'll reopen this issue if it reoccurs.
