### ISSUE TITLE
player hangs with errors between songs

### ISSUE THREAD

**Issue by lordB8r** [PromyLOPh/pianobar#581]
The following keep showing up when I'm playing a track. Not sure why it hangs, but it stops play for a while. 

Traceback (most recent call last):
  File "/Users/lordB8r/.config/pianobar/scrobble.py", line 47, in <module>
    main()
  File "/Users/lordB8r/.config/pianobar/scrobble.py", line 44, in main
    network.update_now_playing(artist = artist, album = album, title = title, duration = song_duration)
  File "/Users/lordB8r/.config/pianobar/pylast.py", line 465, in update_now_playing
    _Request(self, "track.updateNowPlaying", params).execute()
  File "/Users/lordB8r/.config/pianobar/pylast.py", line 828, in execute
    response = self._download_response()
  File "/Users/lordB8r/.config/pianobar/pylast.py", line 819, in _download_response
    self._check_response_for_errors(response_text)
  File "/Users/lordB8r/.config/pianobar/pylast.py", line 846, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: Invalid session key - Please re-authenticate```

I try ctrl + c and get this:

  File "/Users/lordB8r/.config/pianobar/scrobble.py", line 47, in <module>
    main()
  File "/Users/lordB8r/.config/pianobar/scrobble.py", line 38, in main
    network = pylast.LastFMNetwork(api_key = API_KEY, api_secret = API_SECRET, username = USERNAME, password_hash = pylast.md5(PASSWORD))
  File "/Users/lordB8r/.config/pianobar/pylast.py", line 578, in **init**
    "user": "user/%(name)s",
  File "/Users/lordB8r/.config/pianobar/pylast.py", line 165, in **init**
    self.session_key = sk_gen.get_session_key(self.username, self.password_hash)
  File "/Users/lordB8r/.config/pianobar/pylast.py", line 929, in get_session_key
    doc = request.execute()
  File "/Users/lordB8r/.config/pianobar/pylast.py", line 828, in execute
    response = self._download_response()
  File "/Users/lordB8r/.config/pianobar/pylast.py", line 815, in _download_response
    response_text = _unicode(conn.getresponse().read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
/!\ Unable to open audio file (Immediate exit requested)

Then play resumes for the song, then hangs again

**Comment by PromyLOPh** [comment]
pianobar waits for the eventcmd script (Python in this case) to exit,
before it continues with the next song. Looks like yours doesn’t do
that, does it?
